### ISSUE TITLE
SharePoint 2019 on prem

### ISSUE THREAD

**Issue by JoelHJ** [mayur1711/configurable-image-slider-webpart#1]
Hi,

Will this work on SP 2019 on Prem if I have a local CDN?

**Comment by mayur1711** [comment]
Hey Joel,

Yes the web part will work with SP 2019. I can confirm this as it was initially designed for SP 2019 and later on re-created for SP Online. The code base will be same except for the dependencies as not all latest packages are directly compatible with SP 2019.

Below is the snap of **_package.json_** of the SP 2019 version of the webpart. Unfortunately, I can not share the SP 2019 compatible solution due to compliance reasons.

```
"dependencies": {
"@microsoft/sp-core-library": "~1.4.0",
"@microsoft/sp-lodash-subset": "~1.4.0",
"@microsoft/sp-office-ui-fabric-core": "~1.4.0",
"@microsoft/sp-webpart-base": "~1.4.0",
"@types/react-bootstrap": "^0.32.0",
"react": "15.6.2",
"react-bootstrap": "^0.32.0",
"react-dom": "15.6.2",
"sp-client-custom-fields": "^1.3.7"
},
"devDependencies": {
"@types/react": "15.6.6", 
"@types/react-dom": "15.5.6", 
"@microsoft/sp-build-web": "~1.4.1",  
"@microsoft/sp-module-interfaces": "~1.4.1",
"@microsoft/sp-webpart-workbench": "~1.4.1",
"gulp": "~3.9.1",
"@types/chai": "3.4.34",
"@types/mocha": "2.2.38",
"ajv": "~5.2.2",
"@types/webpack-env": "1.13.1",
"@types/es6-promise": "0.0.33"
}
```
